Component/AdminMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Component
{
    [ViewComponent]
    public class AdminMenuViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var Menu = new ParamMenuAdminComponent
            {
                ListCategory = Article_Category_Data.ListAsMenu(TN_Helper.PartnerNumber, out _),
                ListProduct = Product_Category_Data.ListAsMenu(TN_Helper.PartnerNumber, out _)
            };
            return View("~/Views/Admin/Components/Menu.cshtml", Menu);
        }
    }
}

Controllers/AdminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using HttpGetAttribute = Microsoft.AspNetCore.Mvc.HttpGetAttribute;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;
using JsonResult = Microsoft.AspNetCore.Mvc.JsonResult;
using RouteAttribute = Microsoft.AspNetCore.Mvc.RouteAttribute;

namespace WebSite.Controllers
{
    public class AdminController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        #region [--banner--]
        [Route("banner")]
        public IActionResult Banner()
        {
            ViewBag.ListBanner = Banner_Data.List(UserLog.PartnerNumber, out string Error);
            TempData["Error"] = Error;
            return View();
        }
        [HttpPost]
        [DisplayName("Cập nhật banner website")]
        public async Task<IActionResult> Save_Banner(IFormFile Banner, int BannerKey = 0, string Title = "", string Description = "", string Publish = "false", int Rank = 0)
        {
            Title ??= "";
            Description ??= "";

            var zInfo = new Banner_Info(BannerKey);
            zInfo.Banner.Rank = Rank;
            zInfo.Banner.Title = Title.Trim();
            zInfo.Banner.Description = Description.Trim();
            zInfo.Banner.Publish = Publish.ToBool();

            zInfo.Banner.Partnernumber = UserLog.PartnerNumber;
            zInfo.Banner.CreatedBy = UserLog.UserKey;
            zInfo.Banner.CreatedName = UserLog.UserName;
            zInfo.Banner.ModifiedBy = UserLog.UserKey;
            zInfo.Banner.ModifiedName = UserLog.UserName;

            string Uploaded = await TN_Helper.UploadAsync(Banner, "Banner");
            if (Uploaded.Length > 0)
            {
                zInfo.Banner.Url = Uploaded;
            }

            if (zInfo.Banner.BannerKey == 0)
            {
                zInfo.Create_ServerKey();
            }
            else
            {
                zInfo.Update();
            }

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {

            }
            else
            {
                TempData["Error"] = zInfo.Message.GetFirstLine().GetFirstLine();
            }

            return RedirectToAction("Banner");
        }
        [HttpGet]
        [DisplayName("Chi tiết banner website")]
        public JsonResult Get_Banner(int BannerKey)
        {
            var zResult = new ServerResult();
            var zInfo = new Banner_Info(BannerKey);
            var zModel = zInfo.Banner;
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                zResult.Data = JsonConvert.SerializeObject(zModel);
                return Json(zResult);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
                return Json(zResult);
            }
        }
        [HttpPost]
        [DisplayName("Xóa banner website")]
        public JsonResult Delete_Banner(int BannerKey)
        {
            var zResult = new ServerResult();
            var zInfo = new Banner_Info();
            zInfo.Banner.BannerKey = BannerKey;
            zInfo.Banner.ModifiedName = UserLog.UserName;
            zInfo.Banner.ModifiedBy = UserLog.UserKey;
            zInfo.Delete();
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
            }
            return Json(zResult);
        }
        public JsonResult Activate_Banner(int BannerKey)
        {
            var zResult = new ServerResult();
            var zInfo = new Banner_Info();
            zInfo.Banner.ModifiedName = UserLog.UserName;
            zInfo.Banner.ModifiedBy = UserLog.UserKey;
            zInfo.SetActivate(BannerKey);
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                zResult.Data = string.Empty;
                zResult.Message = string.Empty;
            }
            else
            {
                zResult.Success = false;
                zResult.Data = string.Empty;
                zResult.Message = zInfo.Message.GetFirstLine();
            }
            return Json(zResult);
        }
        #endregion

        #region [--Danh mục--]
        [Route("danh-muc")]
        public IActionResult Article_Category()
        {
            ViewBag.ListCategory = Article_Category_Data.ListCategory(UserLog.PartnerNumber, out string Error);
            TempData["Error"] = Error;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Save_Article_Category(IFormFile ArticleBanner, int CategoryKey = 0, string CategoryName = "", string Description = "", int Parent = 0, int Rank = 0)
        {
            CategoryName ??= "";
            Description ??= "";

            var zInfo = new Article_Category_Info(CategoryKey);
            zInfo.Article_Category.CategoryName = CategoryName.Trim();
            zInfo.Article_Category.Description = Description.Trim();
            zInfo.Article_Category.Publish = true;
            zInfo.Article_Category.Parent = Parent;
            zInfo.Article_Category.Rank = Rank;
            zInfo.Article_Category.PartnerNumber = UserLog.PartnerNumber;
            zInfo.Article_Category.CreatedBy = UserLog.UserKey;
            zInfo.Article_Category.CreatedName = UserLog.UserName;
            zInfo.Article_Category.ModifiedBy = UserLog.UserKey;
            zInfo.Article_Category.ModifiedName = UserLog.UserName;

            string Uploaded = await TN_Helper.UploadAsync(ArticleBanner, "ArticleBanner");
            if (Uploaded.Length > 0)
            {
                zInfo.Article_Category.Image = Uploaded;
            }

            if (zInfo.Article_Category.CategoryKey == 0)
            {
                zInfo.Create_ServerKey();
            }
            else
            {
                zInfo.Update();
            }

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {

            }
            else
            {
                TempData["Error"] = zInfo.Message.GetFirstLine().GetFirstLine();
            }

            return RedirectToAction("Article_Category");
        }
        [HttpGet]
        public JsonResult Edit_Article_Category(int CategoryKey)
        {
            var zResult = new ServerResult();
            var zInfo = new Article_Category_Info(CategoryKey);
            var zModel = zInfo.Article_Category;
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                zResult.Data = JsonConvert.SerializeObject(zModel);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
            }
            return Json(zResult);
        }
        [HttpPost]
        public JsonResult Delete_Article_Category(int CategoryKey)
        {
            var zResult = new ServerResult();
            var zInfo = new Article_Category_Info();
            zInfo.Article_Category.CategoryKey = CategoryKey;
            zInfo.Delete();
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
            }
            return Json(zResult);
        }
        [HttpPost]
        public JsonResult Publish_Article_Category(int CategoryKey)
        {
            var zResult = new ServerResult();
            var zInfo = new Article_Category_Info();
            zInfo.Article_Category.ModifiedName = UserLog.UserName;
            zInfo.Article_Category.ModifiedBy = UserLog.UserKey;
            zInfo.SetPublish(CategoryKey);

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                zResult.Message = string.Empty;
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
            }

            return Json(zResult);
        }
        #endregion

        #region[--Noi dung--]
        [Route("cac-bai-viet/{CategoryKey}")]
        public IActionResult Article_List(int CategoryKey)
        {
            ViewBag.CategoryName = new Article_Category_Info(CategoryKey).Article_Category.CategoryName;
            ViewBag.ListArticle = Article_Data.List(UserLog.PartnerNumber, CategoryKey, out string Error);
            TempData["Error"] = Error;
            return View("~/Views/Admin/Article_List.cshtml");

        }

        [Route("viet-bai/{CategoryKey}/{ArticleKey}")]
        public IActionResult Article_Edit(string ArticleKey, int CategoryKey)
        {
            ArticleKey ??= "";
            var zInfo = new Article_Info(ArticleKey);
            string CategoryName;
            if (ArticleKey == string.Empty)
            {
                CategoryName = new Article_Category_Info(CategoryKey).Article_Category.CategoryName;
            }
            else
            {
                CategoryName = zInfo.Article.CategoryName;
            }

            ViewBag.CategoryKey = CategoryKey;
            ViewBag.CategoryName = CategoryName;
            return View("~/Views/Admin/Article_Edit.cshtml", zInfo.Article);
        }

Controllers/AuthController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Controllers
{
    public class AuthController : Controller
    {

        [Route("dang-nhap")]
        public IActionResult Index()
        {
            if (Request.Cookies["auth"] != null)
            {
                var auth = Request.Cookies["auth"];
                var obj = JsonConvert.DeserializeObject<Auth>(auth);
                ViewBag.UserName = obj.UserName;
                ViewBag.Password = obj.Password;
            }

            ViewBag.Message = "NotAuthen";
            return View();
        }
        public IActionResult SignIn(string UserName, string Password)
        {
            if (Password.Length < 28)
            {
                Password = TN_Utils.HashPass(Password);
            }

            var zInfo = new User_Info(UserName, Password);
            if (zInfo.Code == "200")
            {
                var key = "UserLogged";
                var obj = JsonConvert.SerializeObject(zInfo.User);
                HttpContext.Session.SetString(key, obj);

                ViewBag.Message = "IsAuthen";

                //Update Logged
                zInfo.UpdateLogged();

                //Cookies login
                Response.Cookies.Append("auth", JsonConvert.SerializeObject(new Auth
                {
                    UserName = UserName,
                    Password = Password
                }));

                //Logo Admin
                var Logo = new Partner_Info(zInfo.User.PartnerNumber).Partner.Logo_Large;
                Response.Cookies.Append("logo", Logo);
            }
            else
            {
                ViewBag.Message = "405";
            }

            return View("~/Views/Auth/Index.cshtml");
        }
    }
}

Views/Admin/Article_Edit.cshtml
@model Article_Model
@{
    ViewBag.Title = "Article";
    Layout = "~/Views/Admin/_Layout.cshtml";
}
<header class="page-header">
    <h2>Bài viết</h2>
    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="#">
                    <i class="fas fa-home"></i>
                </a>
            </li>
            <li></li>
        </ol>
    </div>
</header>
@if (TempData["Error"] != null &&
       TempData["Error"].ToString() != string.Empty)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>@TempData["Error"]</strong>
    </div>
}
<form class="ecommerce-form action-buttons-fixed row"
      enctype="multipart/form-data" method="post"
      action="@Url.Action("Save_Article", "Admin")">
    <div class="col-md-8">
        <div class="form-group">
            <label for="txt_ArticleName" class="control-label">Tiêu đề bài viết</label>
            <input type="text" class="form-control" id="txt_ArticleName" name="ArticleName" value="@Model.ArticleName" placeholder="Tiêu đề" required="">
        </div>
        <div class="form-group">
            <div class="">
                <label for="txt_Summarize" class="control-label">Tóm tắt nội dung</label>
                <textarea id="txt_Summarize" rows="5" class="form-control" name="Summarize" required="">@Model.Summarize</textarea>
            </div>
        </div>
        <div class="form-group">
            <label for="txt_ArticleContent" class="control-label">Nội dung chi tiết</label>
            <textarea id="txt_ArticleContent" rows="4" cols="10" name="ArticleContent" style="min-height:500px;">@Model.ArticleContent</textarea>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-body bg-white">
                <div class="form-group text-center">
                    @if (Model.ImageLarge.Length <= 0)
                    {
                        <img id="imgpreview" src="~/themes/admin/img/noimg.png" alt="your image" style="max-height: 200px; max-width:100%" />
                    }
                    else
                    {
                        <img id="imgpreview" src="@Url.Content(Model.ImageLarge)" alt="your image" style="max-height: 200px; max-width: 100%" />
                    }
                    <input type="file" id="ArticlePicture" class="form-control d-none" name="ArticlePicture" accept="image/*;capture=camera" />
                </div>
                <div class="form-group d-none">
                    <label for="" class="control-label">Tập tin đính kèm</label>
                    @if (Model.FileAttack.Length > 0)
                    {
                        <a href="@Model.FileAttack">
                            <i class="fas fa-paperclip"></i>
                            Tải xuống
                        </a>
                    }
                    <br />
                    <input id="ArticleAttach" type="file" name="ArticleAttach" />
                </div>
                <hr />
                <div class="form-group mb-0">
                    <label for="" class="control-label">Danh mục: @ViewBag.CategoryName</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row action-buttons">
        <div class="col-12 col-md-auto">
            <button type="submit" id="btn_Save" class="submit-button btn btn-primary btn-px-4 py-3 d-flex align-items-center font-weight-semibold line-height-1" data-loading-text="Loading..." onclick="Utils.LoadIn();">
                <i class="bx bx-save text-4 mr-2"></i>
                Cập nhật
            </button>
        </div>
        <div class="col-12 col-md-auto px-md-0 mt-3 mt-md-0">
            <button type="button" class="cancel-button btn btn-light btn-px-4 py-3 border font-weight-semibold text-color-dark text-3"
                    onclick="GoBack()">
                Quay về
            </button>
        </div>
        <div class="col-12 col-md-auto ml-md-auto mt-3 mt-md-0">
            <button type="button" id="btn_Delete" class="delete-button btn btn-danger btn-px-4 py-3 d-flex align-items-center font-weight-semibold line-height-1"
                    onclick="Delete('@Model.ArticleKey')">
                <i class="bx bx-trash text-4 mr-2"></i>
                Xóa
            </button>
        </div>
    </div>

    <input id="txt_CategoryKey" type="hidden" value="@ViewBag.CategoryKey" name="CategoryKey" />
    <input id="txt_ArticleKey" type="hidden" value="@Model.ArticleKey" name="ArticleKey" />
</form>

@section scripts{
    <script src="https://cdn.tiny.cloud/1/folv8giv7uv90noxx9w7c88d6er7ryqrfdx8ut7vi96h233p/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        var URL_List = "@Url.Action("Article_List", "Admin", new { CategoryKey = "_key_" })";
        var URL_Delete = "@Url.Action("Delete_Article", "Admin")";

        function GoBack() {
            var CategoryKey = $("#txt_CategoryKey").val();
            URL_List = URL_List.replace("_key_", CategoryKey);
            window.location = URL_List;
        };
        function Delete_Article(Key) {
            $.confirm({
                type: "red",
                typeAnimated: true,
                title: "Cảnh báo !.",
                content: "Bạn có chắc xóa thông tin này ?.",
                buttons: {
                    confirm: {
                        text: "Đồng ý",
                        btnClass: "btn-red",
                        action: function () {
                            $.ajax({
                                url: URL_Delete,
                                type: "POST",
                                data: {
                                    "ArticleKey": Key
                                },
                                beforeSend: function () {
                                },
                                success: function (r) {
                                    if (r.success) {
                                        GoBack();
                                    }
                                    else {
                                        Utils.OpenNotify(r.message, "Thông báo", "error");
                                    }
                                },
                                error: function (err) {
                                    Utils.OpenNotify(err.responseText, "Thông báo", "error");
                                },
                                complete: function () {
                                }
                            });
                        }
                    },
                    cancel: {
                        text: "Hủy",
                    }
                }
            });
        };
        $(document).ready(function () {
            $("html").addClass("sidebar-left-collapsed");
            $("#chkPublish").change(function () {
                if (this.checked) {
                    $("#txt_Publish").val("true");
                }
                else {
                    $("#txt_Publish").val("false");
                }
            });
            $("#imgpreview").click(function () {
                $("#ArticlePicture").trigger("click");
            });
            $("#ArticlePicture").change(function () {
                Utils.PreviewImg(this, "#imgpreview");
                var str = $("#imgpreview").attr("src");
            });

            tinymce.init({
                selector: "textarea#txt_ArticleContent",
                paste_data_images: true,
                height: 500,
                menubar: false,
                plugins: [
                    "image", "table", "fullscreen",
                    "advlist autolink lists link image charmap print preview anchor",
                    "searchreplace visualblocks code fullscreen",
                    "insertdatetime media table paste code help wordcount"
                ],
                toolbar:
                    "fullscreen | image |" +
                    "table |" +
                    "undo redo | formatselect | " +
                    "bold italic backcolor | alignleft aligncenter " +
                    "alignright alignjustify | bullist numlist outdent indent | " +
                    "removeformat | help",
                content_style: "body { font-family:Helvetica,Arial,sans-serif; font-size:14px }"
            });
        });
    </script>
}

Views/Admin/Index.cshtml
@{
    Layout = "~/Views/Admin/_Layout.cshtml";
}

Views/Admin/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    var logo = HttpContextAccessor.HttpContext.Request.Cookies["logo"];
    if (logo == null || logo == string.Empty)
    {
        logo = "~/themes/admin/img/logodefault.png";
    }
}
<!DOCTYPE html>
<html class="fixed sidebar-light">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quản trị nội dung</title>
    <!-- Web Fonts  -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800|Shadows+Into+Light"
        rel="stylesheet" type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="@Url.Content("~/themes/admin/vendor/bootstrap/css/bootstrap.css")" />
    <link rel="stylesheet" href="@Url.Content("~/themes/admin/vendor/animate/animate.compat.css")" />

    <link rel="stylesheet" href="@Url.Content("~/themes/admin/vendor/font-awesome/css/all.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/themes/admin/vendor/boxicons/css/boxicons.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/themes/admin/vendor/magnific-popup/magnific-popup.css")" />
    <link rel="stylesheet"
        href="@Url.Content("~/themes/admin/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.css")" />

    <!-- Specific Page Vendor CSS -->
    <link rel="stylesheet" href="@Url.Content("~/themes/admin/vendor/jquery-ui/jquery-ui.css")" />
    <link rel="stylesheet" href="@Url.Content("~/themes/admin/vendor/jquery-ui/jquery-ui.theme.css")" />
    <link rel="stylesheet" href="@Url.Content("~/themes/admin/vendor/jquery-confirm/css/jquery-confirm.css")" />
    <link rel="stylesheet" href="@Url.Content("~/themes/admin/vendor/select2/css/select2.css")" />
    <link rel="stylesheet" href="@Url.Content("~/themes/admin/vendor/pnotify/pnotify.custom.css")" />
    <!-- themes CSS -->
    <link rel="stylesheet" href="@Url.Content("~/themes/admin/css/theme.css")" />
    <!-- Skin CSS -->
    <link rel="stylesheet" href="@Url.Content("~/themes/admin/css/skins/default.css")" />
    <link rel="stylesheet" href="@Url.Content("~/themes/admin/css/custom.css")" />
    @await RenderSectionAsync("Styles", false)
    <!-- Head Libs -->
    <script src="@Url.Content("~/themes/admin/vendor/modernizr/modernizr.js")"></script>
</head>
<body data-loading-overlay class="loading-overlay-showing">
    <div class="loading-overlay">
        <div class="bounce-loader">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <section class="body">
        <header class="header">
            <div class="logo-container">
                <a href="@Url.Action("Index","Home")" class="logo">
                    <img src="@Url.Content(logo)" height="35" alt="logo">
                </a>
                <div class="d-md-none toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html"
                    data-fire-event="sidebar-left-opened">
                    <i class="fas fa-bars" aria-label="Toggle sidebar"></i>
                </div>
            </div>

            <!-- start: search & user box -->
            <div class="header-right">
                <div id="userbox" class="userbox">
                    <a href="#" data-toggle="dropdown">
                        <figure class="profile-picture">
                            <img src="~/themes/admin/img/avatar.jpg" alt="Joseph Doe" class="rounded-circle"
                                data-lock-picture="img/!logged-user.jpg" style="object-fit:cover" height="35">
                        </figure>
                        <div class="profile-info" data-lock-name="John Doe" data-lock-email="..">
                            <span class="name">Quản trị viên</span>
                        </div>
                        <i class="fa custom-caret"></i>
                    </a>
                    <div class="dropdown-menu">
                        <ul class="list-unstyled mb-2">
                            <li>
                                <a role="menuitem" asp-controller="Auth" asp-action="Index">
                                    <i class="fas fa-power-off"></i>
                                    Đăng xuất
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- end: search & user box -->
        </header>
        <div class="inner-wrapper" style="background-image: url('')">
            <aside id="sidebar-left" class="sidebar-left">
                <div class="sidebar-header">
                    <div class="sidebar-title">

                    </div>
                    <div class="sidebar-toggle d-none d-md-block" data-toggle-class="sidebar-left-collapsed"
                        data-target="html" data-fire-event="sidebar-left-toggle">
                        <i class="fas fa-bars" aria-label="Toggle sidebar"></i>
                    </div>
                </div>
                <div class="nano">
                    <div class="nano-content">
                        <nav id="menu" class="nav-main" role="navigation">
                            @await Component.InvokeAsync("AdminMenu")
                        </nav>
                    </div>
                </div>
            </aside>
            <section role="main" class="content-body content-body-modern mt-0">
                @RenderBody()
            </section>
        </div>
    </section>
    <script src="@Url.Content("~/themes/admin/vendor/jquery/jquery.min.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/jquery-browser-mobile/jquery.browser.mobile.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/popper/umd/popper.min.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/bootstrap/js/bootstrap.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/common/common.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/nanoscroller/nanoscroller.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/magnific-popup/jquery.magnific-popup.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/moment/moment.js")"></script>
    <!-- themes Base, Components and Settings -->
    <script src="@Url.Content("~/themes/admin/vendor/pnotify/pnotify.custom.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/select2/js/select2.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/ios7-switch/ios7-switch.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/autosize/autosize.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/jquery-validation/jquery.validate.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/bootstrap-wizard/jquery.bootstrap.wizard.js")"></script>
    <script src="@Url.Content("~/themes/admin/vendor/jquery-confirm/js/jquery-confirm.js")"></script>
    <script src="@Url.Content("~/themes/admin/js/jquery.number.js")"></script>
    <script src="@Url.Content("~/themes/admin/js/theme.js")"></script>
    <!-- themes Initialization Files -->
    <script src="@Url.Content("~/themes/admin/js/Utils.js")"></script>
    <script src="@Url.Content("~/themes/admin/js/session-timeout.js")"></script>
    <script src="@Url.Content("~/themes/admin/js/custom.js")"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="@Url.Content("~/themes/admin/js/theme.init.js")"></script>
</body>
</html>