Component/AdminMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Component
{
    [ViewComponent]
    public class AdminMenuViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var Menu = new ParamMenuAdminComponent
            {
                ListCategory = Article_Category_Data.ListAsMenu(TN_Helper.PartnerNumber, out _),
                ListProduct = Product_Category_Data.ListAsMenu(TN_Helper.PartnerNumber, out _)
            };
            return View("~/Views/Admin/Components/Menu.cshtml", Menu);
        }
    }
}

Component/FrontEnd/BannerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Component
{
    [ViewComponent]
    public class BannerViewComponent: ViewComponent
    {
       
        public IViewComponentResult Invoke()
        {
            var zList = Banner_Data.List(TN_Helper.PartnerNumber, out _);
            zList = zList.Where(s => s.Publish == true).ToList();
            return View("~/Views/Shared/Components/Banner.cshtml", zList);
        }
    }
}

Component/FrontEnd/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Component
{
    [ViewComponent]
    public class FooterViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string ID)
        {
            string Logo = "";
            var zPartner = new Partner_Info(TN_Helper.PartnerNumber);
            if (zPartner.Partner.Logo_Large.Length > 0)
            {
                Logo = zPartner.Partner.Logo_Large;
            }

            ViewBag.Logo = Logo;

            var zConfig = new Config_Info(ID, TN_Helper.PartnerNumber);
            var zParent = zConfig.Config.ConfigKey;
            var zList = Config_Data.List(TN_Helper.PartnerNumber, zParent, out _);
            var zCOT1 = zList.SingleOrDefault(s => s.ConfigID == "COT1");
            var zCOT2 = zList.Where(s => s.ConfigID == "COT2").ToList();           
            var zCOT3= zList.Where(s => s.ConfigID == "COT3").ToList();
            if (zCOT1 != null)
            {
                string Key = zCOT1.Value;
                var zContact = new Article_Info(Key).Article.Summarize;
                ViewBag.Contact = zContact;
            }

            ViewBag.COT3 = zCOT3;
            ViewBag.COT2 = zCOT2;

            return View("~/Views/Shared/Components/Footer.cshtml");
        }
    }
}

Component/FrontEnd/Group2ViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Component
{
    [ViewComponent]
    public class Group2ViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string ID)
        {
            var zInfo = new Config_Info(ID, TN_Helper.PartnerNumber);
            ViewBag.Title = zInfo.Config.Name;

            var zParent = zInfo.Config.ConfigKey;

            var zList = Config_Data.List(TN_Helper.PartnerNumber, zParent, out _);
            var zListBog = new List<Article_Model>();
            foreach (var rec in zList)
            {
                string Key = rec.Value;
                var Model = new Article_Info(Key).Article;
                zListBog.Add(Model);
            }

            return View("~/Views/Shared/Components/Group2.cshtml", zListBog);
        }
    }
}

Component/FrontEnd/Group3ViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Component
{
    [ViewComponent]
    public class Group3ViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string ID)
        {
            var zInfo = new Config_Info(ID, TN_Helper.PartnerNumber);
            ViewBag.Title = zInfo.Config.Name;

            var zParent = zInfo.Config.ConfigKey;
            var zList = Config_Data.List(TN_Helper.PartnerNumber, zParent, out _);
           
            return View("~/Views/Shared/Components/Group3.cshtml", zList);
        }
    }
}

Component/FrontEnd/Group4ViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Component.FrontEnd
{
    [ViewComponent]
    public class Group4ViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string ID)
        {
            var zInfo = new Config_Info(ID, TN_Helper.PartnerNumber);
            ViewBag.Title = zInfo.Config.Name;

            var zCategory = zInfo.Config.Value;
            var zList = Article_Data.ListShow(TN_Helper.PartnerNumber, zCategory.ToInt(), out _);

            return View("~/Views/Shared/Components/Group4.cshtml", zList);
        }
    }
}

Component/FrontEnd/HeaderMiddleViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Component
{
    [ViewComponent]
    public class HeaderMiddleViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            string Logo = "";
            var zInfo = new Partner_Info(TN_Helper.PartnerNumber);
            if (zInfo.Partner.Logo_Large.Length > 0)
            {
                Logo = zInfo.Partner.Logo_Large;
            }
            else
            {
                Logo = "~/themes/admin/img/logodefault.png";
            }

            ViewBag.Logo = Logo;

            return View("~/Views/Shared/Components/HeaderMiddle.cshtml");
        }
    }
}

Component/FrontEnd/LeftArticleViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Component
{
    [ViewComponent]
    public class LeftArticleViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke(int CategoryKey)
        {
            //các bài viết
            var zList = Article_Data.ListShow(TN_Helper.PartnerNumber, CategoryKey, out _);  
            
            //danh mục
            //Article_Category_Data.List(TN_Helper.PartnerNumber, CategoryKey, out _);

            return View("~/Views/Shared/Components/LeftArticle.cshtml", zList);
        }
    }
}

Component/FrontEnd/LeftProductViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WebSite.Component
{
    [ViewComponent]
    public class LeftProductViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(int CategoryKey)
        {
            var zCategory = new Product_Category_Info(CategoryKey).Product_Category;
            ViewBag.CategoryName = zCategory.CategoryName;
            ViewBag.CategoryKey = zCategory.CategoryKey;

            var zList = Product_Category_Data.List(TN_Helper.PartnerNumber, CategoryKey, out _);

            if (zList.Count <= 0)
            {
                zList = Product_Category_Data.List(TN_Helper.PartnerNumber, zCategory.Parent, out _);
            }

            return View("~/Views/Shared/Components/LeftProduct.cshtml", zList);
        }
    }
}

Component/FrontEnd/MobileMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace WebSite.Component
{
    [ViewComponent]
    public class MobileMenuViewComponent : ViewComponent
    {
       
        public IViewComponentResult Invoke()
        {
            var zList = Menu_WebSite_Data.ListShow(TN_Helper.PartnerNumber, out _);
            zList = zList.Where(s => s.Publish == true).ToList();
            return View("~/Views/Shared/Components/MobileMenu.cshtml", zList);
        }
    }
}

Controllers/MemberController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;

namespace WebSite.Controllers
{
    public class MemberController : Controller
    {
        public IActionResult Login()
        {
            if (Request.Cookies["member"] != null)
            {
                var auth = Request.Cookies["member"];
                var obj = JsonConvert.DeserializeObject<Auth>(auth);
                ViewBag.UserName = obj.UserName;
                ViewBag.Password = obj.Password;
            }

            return View();
        }

        public IActionResult Login_Normal(string Email, string Password)
        {
            Email ??= "";
            Password ??= "";

            Customer_Info zInfo;
            if (Password.Length != 28)
            {
                zInfo = new Customer_Info(Email, TN_Utils.HashPass(Password), true);
            }
            else
            {
                zInfo = new Customer_Info(Email, Password, true);
            }

            if (zInfo.Code == "200")
            {
                var key = "MemberLogged";
                var obj = JsonConvert.SerializeObject(zInfo.Customer);
                HttpContext.Session.SetString(key, obj);

                ViewBag.Message = "IsAuthen";

                //Update Logged
                zInfo.UpdateLogged();

                //Cookies login
                Response.Cookies.Append("member", JsonConvert.SerializeObject(new Auth
                {
                    ID = zInfo.Customer.CustomerKey,
                    UserName = Email,
                    Password = TN_Utils.HashPass(Password)
                }));
            }

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Register(string RegEmail, string RegPassword)
        {
            RegEmail ??= "";
            RegPassword ??= "";

            var jResult = ExistMember(RegEmail).Value as ServerResult;
            if (!jResult.Success)
            {
                var zInfo = new Customer_Info();
                zInfo.Customer.Email = RegEmail;
                zInfo.Customer.Password = TN_Utils.HashPass(RegPassword);
                zInfo.Customer.PartnerNumber = TN_Helper.PartnerNumber;
                zInfo.Customer.Referrer = UriHelper.GetDisplayUrl(Request);
                zInfo.Create_ServerKey();
            }
            else
            {

            }

            return View();
        }

        public JsonResult ExistMember(string UserName)
        {
            var zResult = new ServerResult();
            var zInfo = new Customer_Info(UserName, true);
            if (zInfo.Code == "200")
            {
                zResult.Success = true;
                zResult.Message = "Tài khoản này đã có rồi vui lòng nhâp lại !.";
            }
            else
            {
                zResult.Success = false;
            }

            return Json(zResult);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult AddToCart(string ProductKey)
        {
            var zResult = new ServerResult();
            try
            {
                string sOrder = HttpContext.Session.GetString("Order");

                Order_Model zOrder;
                if (!string.IsNullOrEmpty(sOrder))
                {
                    zOrder = JsonConvert.DeserializeObject<Order_Model>(sOrder);
                }
                else
                {
                    zOrder = new Order_Model();
                }

                Order_Item_Model zItem = zOrder.ListItem.SingleOrDefault(s => s.ObjectKey == ProductKey);
                if (zItem != null)
                {
                    zItem.Quantity++;
                    zItem.Amount = zItem.Quantity * zItem.ObjectPrice;
                }
                else
                {
                    zItem = new Order_Item_Model();
                    var Product = new Product_Info(ProductKey).Product;

                    zItem.ObjectKey = Product.ProductKey;
                    zItem.ObjectName = Product.ProductName;
                    zItem.ObjectPrice = Product.SalePrice;
                    zItem.Quantity = 1;
                    zItem.UnitKey = Product.StandardUnitKey;
                    zItem.UnitName = Product.StandardUnitName;
                    zItem.Amount = Product.SalePrice;
                    zItem.PhotoPath = Product.PhotoPath;

                    zOrder.ListItem.Add(zItem);
                }

                HttpContext.Session.SetString("Order", JsonConvert.SerializeObject(zOrder));
                zResult.Success = true;
            }
            catch (Exception ex)
            {
                zResult.Success = false;
                zResult.Message = ex.ToString().GetFirstLine();
            }

            return Json(zResult);
        }
        [HttpPost]
        public JsonResult RemoveCart(string ProductKey)
        {
            var zResult = new ServerResult();
            try
            {
                string sOrder = HttpContext.Session.GetString("Order");
                var zOrder = JsonConvert.DeserializeObject<Order_Model>(sOrder);
                var zItem = zOrder.ListItem.SingleOrDefault(s => s.ObjectKey == ProductKey);
                if (zItem != null && zItem.Quantity > 1)
                {
                    zItem.Quantity--;
                }
                else
                {
                    zOrder.ListItem.Remove(zItem);
                }

                HttpContext.Session.SetString("Order", JsonConvert.SerializeObject(zOrder));
                zResult.Success = true;
            }
            catch (Exception ex)
            {
                zResult.Message = ex.ToString().GetFirstLine();
                zResult.Success = false;
            }
            return Json(zResult);
        }

        [Route("gio-hang")]
        public IActionResult Cart()
        {
            Order_Model zOrder;
            try
            {
                string sOrder = HttpContext.Session.GetString("Order");

                if (!string.IsNullOrEmpty(sOrder))
                {
                    zOrder = JsonConvert.DeserializeObject<Order_Model>(sOrder);
                }
                else
                {
                    zOrder = new Order_Model();
                }


            }
            catch (Exception ex)
            {

                throw;
            }

            return View(zOrder);
        }

        [HttpPost]
        public JsonResult CheckOut(List<ItemCart> data)
        {
            var zResult = new ServerResult();
            string sOrder = HttpContext.Session.GetString("Order");
            if (!string.IsNullOrEmpty(sOrder))
            {
                var zOrder = JsonConvert.DeserializeObject<Order_Model>(sOrder);
                var zList = zOrder.ListItem;

                foreach (var rec in data)
                {
                    var id = rec.id;
                    var amount = rec.qty * rec.price;
                    var des = rec.des;
                    var zItem = zList.Single(s => s.ObjectKey == id);
                    zItem.Quantity = rec.qty;
                    zItem.Amount = amount;
                    zItem.Description = des;
                }

                zOrder.ListItem = zList;
                HttpContext.Session.SetString("Order", JsonConvert.SerializeObject(zOrder));
                zResult.Success = true;
            }
            else
            {
                zResult.Message = "Session is null";
                zResult.Success = false;
            }

            return Json(zResult);
        }
        [HttpPost]
        public JsonResult CancelCart()
        {
            var zResult = new ServerResult();
            zResult.Success = true;
            HttpContext.Session.Clear();
            return Json(zResult);
        }

        [Route("giao-hang")]
        [HttpGet]
        public IActionResult ShippingCart()
        {
            string sOrder = HttpContext.Session.GetString("Order");
            var zOrder = new Order_Model();
            if (!string.IsNullOrEmpty(sOrder))
            {
                zOrder = JsonConvert.DeserializeObject<Order_Model>(sOrder);
            }
            return View(zOrder);
        }

        [HttpPost]
        public IActionResult SaveOrder(string Name, string Phone, string Address, string Description)
        {
            string Key = Guid.NewGuid().ToString();
            string ID = Order_Data.AutoID("ES", TN_Helper.PartnerNumber);
            bool Error = false;
            string Message = "";
            try
            {
                string sOrder = HttpContext.Session.GetString("Order");
                var zOrder = new Order_Model();
                if (!string.IsNullOrEmpty(sOrder))
                {
                    zOrder = JsonConvert.DeserializeObject<Order_Model>(sOrder);
                    zOrder.StatusOrder = 1;
                    zOrder.StatusName = "Chờ xác nhận";
                    zOrder.OrderID = ID;
                    zOrder.OrderKey = Key;
                    zOrder.BuyerName = Name;
                    zOrder.BuyerPhone = Phone;
                    zOrder.BuyerAddress = Address;
                    zOrder.Description = Description;
                    zOrder.OrderDate = DateTime.Now;
                    zOrder.PartnerNumber = TN_Helper.PartnerNumber;
                    zOrder.AmountOrder = zOrder.ListItem.Sum(s => s.Amount);
                    zOrder.CreatedBy = TN_Helper.BusinessName;
                    zOrder.CreatedName = TN_Helper.BusinessName;
                    zOrder.ModifiedBy = TN_Helper.BusinessName;
                    zOrder.ModifiedName = TN_Helper.BusinessName;
                    zOrder.ClearNullable();

Views/Shared/Components/Banner.cshtml
@model List<Banner_Model>

<div class="home-slider owl-carousel owl-theme owl-carousel-lazy show-nav-hover nav-big mb-2 text-uppercase"
     data-owl-options="{
				'loop': true
			}">
    @{
        for (int i = 0; i < Model.Count; i++)
        {

            var zRec = Model[i];
            string UrlPhoto = zRec.Url;

            <div class="home-slide home-slide1 banner">
                <img class="owl-lazy slide-bg" src="@Url.Content(UrlPhoto)" data-src="@Url.Content(UrlPhoto)" alt="slider image">
            </div>
            <!-- End .home-slide -->
        }
    }
</div>
<!-- End .home-slider -->

Views/Shared/Components/Footer.cshtml
@{

    var ListCot3 = new List<Config_Model>();
    if (ViewBag.COT3 != null)
    {
        ListCot3 = ViewBag.COT3 as List<Config_Model>;
    }
}

<footer class="footer bg-dark">
    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="widget">
                        <h4 class="widget-title">Liên hệ</h4>
                        <ul class="contact-info">
                            <li>
                                <strong>Công ty cổ phần TN SOLUTION</strong>
                            </li>
                            <li>
                                <span class="contact-info-label">Địa chỉ</span>
                                96/14 Tân Mỹ, Kp4, P.Tân Thuận Tây, Q7 TPHCM
                            </li>
                            <li>
                                <span class="contact-info-label">Điện thoại</span>
                                <a href="tel:02862706069">(028) 6270 6069</a>
                            </li>
                            <li>
                                <span class="contact-info-label">Hot line</span>
                                <a href="tel:0902106212">090 210 6212</a>
                            </li>
                            <li>
                                <span class="contact-info-label">Email</span>
                                <a href="mailto:info@tnsolution.vn">info@tnsolution.vn</a>
                            </li>
                            <li>
                                <span class="contact-info-label">Giờ làm việc</span>
                                T2 - T7 / 9:30AM - 5:30 PM
                            </li>
                        </ul>                        
                    </div><!-- End .widget -->
                </div><!-- End .col-lg-3 -->

                <div class="col-lg-3 col-sm-6">
                    <div class="widget">
                        <h4 class="widget-title">Hỗ trợ khách hàng</h4>

                        <ul class="links">
                            <li><a href="tel:02862706069">Bảo hành (028) 6270 6069</a></li>
                            <li><a href="tel:0902106212">Hot line 090 210 6212</a></li>
                        </ul>
                    </div><!-- End .widget -->
                </div><!-- End .col-lg-3 -->

                <div class="col-lg-3 col-sm-6">
                    <div class="widget">
                        <h4 class="widget-title">Quy định nhà bán hàng</h4>
                        <ul class="links">
                            @{
                                foreach (var rec in ListCot3)
                                {
                                    string Name = rec.Name;
                                    string Link = "/bai-viet/" + rec.Value;

                                    <li><a href="@Link">@Name</a></li>
                                }
                            }
                        </ul>
                    </div><!-- End .widget -->
                </div><!-- End .col-lg-3 -->

                <div class="col-lg-3 col-sm-6">
                    <div class="widget widget-newsletter">
                        <h4 class="widget-title">Đăng ký nhận tin khuyến mãi</h4>
                        <form action="#" class="mb-0">
                            <input type="email" class="form-control m-b-3" placeholder="Nhập email của bạn" required="">
                            <input type="submit" class="btn btn-primary shadow-none" value="Đăng ký">
                        </form>
                    </div><!-- End .widget -->
                </div><!-- End .col-lg-3 -->
            </div><!-- End .row -->
        </div><!-- End .container -->
    </div><!-- End .footer-middle -->

    <div class="container">
        <div class="footer-bottom d-flex justify-content-between align-items-center flex-wrap">
            <p class="footer-copyright py-3 pr-4 mb-0">Công ty cổ phần TN SOLUTION giấy phép số 0315501585 </p>
            <img src="@Url.Content("~/themes/frontend/images/payments.png") " alt="payment methods" class="footer-payments py-3">
        </div>
        <!-- End .footer-bottom -->
    </div>
    <!-- End .container -->
</footer>

Views/Shared/Components/Group2.cshtml
@using Microsoft.AspNetCore.Html
@model List<Article_Model>
@{
    var Icon = new string[] { "<i class='fas fa-chess-queen'></i>", "<i class='fas fa-chart-line'></i>", "<i class='fas fa-swatchbook'></i>" };
}
<div class="service-section bg-light pb-90" style="padding-top: 50px; margin-top: 20px">
    <div class="container">
        <div class="row text-center mb-10">
            <div class="section-title" data-aos="fade-up" data-aos-delay="100">
                <h3 class="title">@ViewBag.Title</h3>
                Chúng tôi làm việc với sự tư duy sáng tạo, phù hợp với từng khách hàng và cho ra những sản phẩm chuyên nghiệp theo xu hướng mới nhất.
            </div>
        </div>
        <div class="row mb-n10">
            @{
                int no = 0;
                foreach (var record in Model)
                {
                    string Key = record.ArticleKey;
                    string Title = record.ArticleName;
                    string Summarize = record.Summarize;
                    string Link = "/bai-viet/" + Key;

                    <div class="col-lg-4 col-md-6 mb-10">
                        <div class="single-service-wrapper" data-aos="fade-up" data-aos-delay="100">
                            <a href="@Link">
                                <div class="service-icon" style="background-color:#272a73 ">
                                    @(new HtmlString(Icon[no]))
                                </div>
                                <div class="service-content">
                                    <h4 class="title">@Title</h4>
                                    <p class="desc-content">@Summarize</p>
                                </div>
                            </a>
                        </div>
                    </div>

                    no++;
                }
            }
        </div>
    </div>
</div>

Views/Shared/Components/HeaderMiddle.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@{
    var auth = HttpContextAccessor.HttpContext.Request.Cookies["member"];
    var obj = new Auth();
    if (auth != null)
    {
        obj = JsonConvert.DeserializeObject<Auth>(auth);
    }

    string tmp = Context.Session.GetString("Order");
    float total = 0;
    double amount = 0;
    Order_Model Order = new Order_Model();
    if (!string.IsNullOrEmpty(tmp))
    {
        Order = JsonConvert.DeserializeObject<Order_Model>(tmp);
        total = Order.ListItem.Sum(s => s.Quantity);
        amount = Order.ListItem.Sum(s => s.Amount);
    }
}
<div class="header-top d-none">
    <div class="container">
        <div class="header-left d-none d-sm-block">
            <p class="top-message text-uppercase"></p>
        </div><!-- End .header-left -->

        <div class="header-right header-dropdowns ml-0 ml-sm-auto w-sm-100">
            <!-- End .header-dropown -->

            <span class="separator"></span>

            <!-- End .header-dropown -->
            <!-- End .header-dropown -->

            <span class="separator"></span>

            <div class="social-icons">
                <fb:login-button scope="public_profile,email"
                                 onlogin="checkLoginState();">
                </fb:login-button>

            </div><!-- End .social-icons -->
        </div><!-- End .header-right -->
    </div><!-- End .container -->
</div>
<div class="header-middle">
    <div class="container">
        <div class="header-left col-lg-2 w-auto pl-0">
            <button class="mobile-menu-toggler text-primary mr-2" type="button">
                <i class="icon-menu"></i>
            </button>
            <a class="logo" asp-controller="Home" asp-action="Index">
                <img src="@Url.Content(ViewBag.Logo)" alt="Porto Logo" style="height:40px">
            </a>
        </div>
        <!-- End .header-left -->
        <div class="header-right w-lg-max">
            <div class="header-icon header-icon header-search header-search-inline header-search-category w-lg-max text-right"></div>
            <div class="header-contact d-none d-lg-flex pl-4 ml-3 mr-xl-5 pr-4">
                <img alt="phone" src="@Url.Content("~/themes/frontend/images/phone.png")" width="30" height="30" class="pb-1">
                <h6>Bán hàng<a href="tel:0902106212" class="text-dark font1">0902 106 212</a></h6>
            </div>
            @{
                if (obj.UserName != string.Empty)
                {
                    <a asp-controller="Member" asp-action="Index" class="header-icon">
                        <i class="icon-user-2"></i>
                        @obj.UserName
                    </a>
                    <a href="#" class="header-icon">
                        <i class="icon-wishlist-2"></i>
                    </a>
                }
                else
                {
                    <a asp-controller="Member" asp-action="Login" class="header-icon login-link d-none">
                        <i class="icon-user-2"></i>
                    </a>
                }
            }
            <div class="dropdown cart-dropdown">
                <a href="@Url.Action("Cart","Member")" class="dropdown-toggle">
                    <i class="icon-shopping-cart"></i>
                    <span class="cart-count badge-circle" id="cart">@total</span>
                </a>
                @*
                    <div class="dropdown-menu show">
                        <div class="dropdownmenu-wrapper">
                            <div class="dropdown-cart-header">
                                <span>2 Items</span>
                                <a asp-controller="Member" asp-action="Cart" class="float-right">Xem giỏ hàng</a>
                            </div>
                            <div class="dropdown-cart-products">
                                @{
                                    foreach (var rec in Order.ListItem)
                                    {
                                        string Key = rec.ObjectKey;
                                        string Name = rec.ObjectName;
                                        string Price = rec.ObjectPrice.ToString("n0");
                                        string Qty = rec.Quantity.ToString();
                                        string Photo = Url.Content(rec.PhotoPath);

                                        <div class="product">
                                            <div class="product-details">
                                                <h4 class="product-title">
                                                    <a href="@Url.Action("Product_Quick","Home", new {ProductKey = Key })" class="btn-quickview">@Name</a>
                                                </h4>

                                                <span class="cart-product-info">
                                                    <span class="cart-product-qty">@Qty</span>
                                                    x @Price
                                                </span>
                                            </div><!-- End .product-details -->

                                            <figure class="product-image-container">
                                                <a href="@Url.Action("Product_Quick","Home", new {ProductKey = Key })" class="product-image btn-quickview">
                                                    <img src="@Photo" alt="product" width="80" height="80">
                                                </a>
                                                <a href="#" class="btn-remove icon-cancel" title="Remove Product" productkey="@Key"></a>
                                            </figure>
                                        </div>
                                    }
                                }

                                <!-- End .product -->
                            </div>
                            <div class="dropdown-cart-total">
                                <span>Tổng</span>
                                <span class="cart-total-price float-right">@amount.ToString("n0")</span>
                            </div>
                            <!-- End .dropdown-cart-total -->

                            <div class="dropdown-cart-action">
                                <a asp-controller="Member" asp-action="CheckOut" class="btn btn-dark btn-block">Thanh toán</a>
                            </div>
                            <!-- End .dropdown-cart-total -->
                        </div>
                        <!-- End .dropdownmenu-wrapper -->
                    </div>
                    <!-- End .dropdown-menu -->
                *@
            </div>
            <!-- End .dropdown -->
        </div>
        <!-- End .header-right -->
    </div>
    <!-- End .container -->
</div>